###
# About/contact for the site author
#
# name of the author of the site
name = "Coreen"
# description to display in the sidebar
description = "Hi, I'm Coreen. I'm an artist, DIY'er and cook."

# the profile image of the author to display in the sidebar
gravatar = "3b23d20bbce78c5de1bcd7098aa870ba" # md5 hash of your email address # sidebar.html

# contact links to reach the author
#  - `name` is the font-awesome char name
#  - `path` is the link to follow 
contact = [
  { name = "facebook", path = "https://" },
  { name = "twitter", path = "https://twitter.com/svavs" },
  { name = "instagram", path = "https://instagram.com/svavs" },
  { name = "email", path = "" }
]
