###
# About/contact for the site author
#
# name of the author of the site
name = "Coreen"
# description to display in the sidebar
description = "Hi, I'm Coreen. I'm an artist, DIY'er and cook."

# the profile image of the author to display in the sidebar
gravatar = "923727035da6d31ffa53b88d4812ac8d" # md5 hash of your email address # sidebar.html

# contact links to reach the author
#  - `name` is the font-awesome char name
#  - `path` is the link to follow 
contact = [
  { name = "pinterest", path = "https://pinterest.com/Lexingtton/_saved/" },
  { name = "facebook", path = "https://facebook.com/thepeacefulhapplife/" },
  { name = "instagram", path = "https://instagram.com/peacefulhappylife" },
  { name = "twitter", path = "https://twitter.com/PeacefulHappyL1" },
  { name = "tiktok", path = "https://tiktok.com/@peacefulhappylife" },
]
