###
# Structure of the navigation menu in the sidebar
#
#  [[nav]] is required and defines the main voice menu
#  [[nav.sub]] is optional and defines the second level voices
#
#  - `name` is the link's name displayed in the navigation menu
#  - `path` is the site's relative link or the full external link associated to `name`
#

[[nav]]
name = "Home"
path = "/"

[[nav]]
name = "Recipes"
path = "/recipes/"

[[nav]]
name = "DIY"
path = "/diy/"

[[nav]]
name = "Art"
path = "/art/"

[[nav]]
name = "Spiritual"
path = "/spiritual/"

[[nav]]
name = "Blog"
path = "/blog/"

[[nav]]
name = "About"
path = "/about/"
